name: splash
base: core20
version: '1.0'
summary: Your App Description
description: |
  Your detailed app description.

confinement: strict

parts:
  splash:
    plugin: python
    source: .
    build-packages:
      - python3
      - python3-pip
      - python3-dev
      - libgtk-3-dev
      - libwebkit2gtk-4.0-dev
      - build-essential
      - libwxgtk3.0-gtk3-dev
    stage-packages:
      - python3-numpy
      - python3-stl
      - libgtk-3-0
      - libwebkit2gtk-4.0-37

apps:
  splash:
    command: bin/splash

plugs:
  network: {}
  opengl: {}

environment:
  LD_LIBRARY_PATH: $LD_LIBRARY_PATH:$SNAP/usr/lib/$SNAPCRAFT_ARCH_TRIPLET/pulseaudio
